"""Two real concurrent connections; only a newly owned isolated test schema is removed."""

import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from queue import Queue
from uuid import uuid4

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from editingtab_core.authorization import repository, services
from editingtab_core.authorization.bootstrap import bootstrap
from editingtab_core.authorization.models import Role
from editingtab_core.authorization.policy import LastAdministrator
from editingtab_core.identity import services as identity
from editingtab_core.identity.models import Membership

pytestmark = pytest.mark.integration
ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def shared_schema(integration_engine):
    schema = "core_concurrent_" + uuid4().hex
    created = False
    try:
        with integration_engine.begin() as connection:
            assert tuple(
                connection.execute(text("SELECT current_database(), current_user")).one()
            ) == ("editingtab_core_test", "editingtab_test")
            connection.exec_driver_sql(f'CREATE SCHEMA "{schema}"')
            connection.exec_driver_sql(f'SET LOCAL search_path TO "{schema}"')
            config = Config(str(ROOT / "alembic.ini"))
            config.attributes["connection"] = connection
            command.upgrade(config, "head")
        created = True
        yield schema
    finally:
        if created:
            with integration_engine.begin() as connection:
                assert tuple(
                    connection.execute(text("SELECT current_database(), current_user")).one()
                ) == ("editingtab_core_test", "editingtab_test")
                # Exact name generated by this fixture, never a developer schema.
                assert schema.startswith("core_concurrent_") and len(schema) == 48
                connection.exec_driver_sql(f'DROP SCHEMA "{schema}" CASCADE')


def scoped_connection(engine, schema):
    connection = engine.connect()
    connection.exec_driver_sql(f'SET search_path TO "{schema}"')
    connection.commit()
    return connection


def test_concurrent_removal_cannot_remove_both_administrators(
    integration_engine, integration_settings, shared_schema
):
    with (
        scoped_connection(integration_engine, shared_schema) as connection,
        Session(connection) as session,
    ):
        first = identity.create_user(session, email="first@example.test", display_name="First")
        second = identity.create_user(session, email="second@example.test", display_name="Second")
        org = bootstrap(
            session,
            settings=integration_settings,
            email="first@example.test",
            slug="concurrent",
            name="Concurrent",
        )
        second_member = identity.add_membership(session, organization_id=org, user_id=second)
        with session.begin():
            role = session.scalar(select(Role.id).where(Role.organization_id == org))
            first_member = session.scalar(
                select(Membership.id).where(
                    Membership.organization_id == org, Membership.user_id == first
                )
            )
        services.change_assignment(
            session, organization_id=org, actor_id=first, membership_id=second_member, role_id=role
        )
    pids = Queue()

    def remove_self(actor, member):
        with scoped_connection(integration_engine, shared_schema) as connection:
            pid = connection.scalar(text("SELECT pg_backend_pid()"))
            connection.commit()
            pids.put(pid)
            with Session(connection) as session:
                try:
                    services.change_assignment(
                        session,
                        organization_id=org,
                        actor_id=actor,
                        membership_id=member,
                        role_id=role,
                        remove=True,
                    )
                    return "removed"
                except LastAdministrator:
                    return "protected"

    with scoped_connection(integration_engine, shared_schema) as gate:
        gate.execute(
            text("SELECT id FROM core_organizations WHERE id = :id FOR UPDATE"), {"id": org}
        )
        with ThreadPoolExecutor(max_workers=2) as workers:
            futures = [
                workers.submit(remove_self, first, first_member),
                workers.submit(remove_self, second, second_member),
            ]
            try:
                worker_pids = [pids.get(timeout=3), pids.get(timeout=3)]
                deadline = time.monotonic() + 2
                # Prove both transactions overlap and wait on database locks.
                with integration_engine.connect() as observer:
                    while True:
                        waiting = [
                            observer.scalar(
                                text("SELECT cardinality(pg_blocking_pids(:pid)) > 0"), {"pid": pid}
                            )
                            for pid in worker_pids
                        ]
                        if all(waiting):
                            break
                        assert time.monotonic() < deadline, "Workers did not reach concurrent locks"
                        time.sleep(0.01)
            finally:
                gate.rollback()
            assert sorted(future.result(timeout=5) for future in futures) == [
                "protected",
                "removed",
            ]
    with (
        scoped_connection(integration_engine, shared_schema) as connection,
        Session(connection) as session,
    ):
        assert repository.has_administrator(session, org)
        remaining = session.execute(
            text("SELECT count(*) FROM core_membership_roles WHERE organization_id = :id"),
            {"id": org},
        ).scalar_one()
        assert remaining == 1
        assert (
            session.execute(
                text("SELECT count(*) FROM core_role_audit WHERE action = 'assignment.removed'")
            ).scalar_one()
            == 1
        )


def test_concurrent_initial_platform_bootstraps_allow_exactly_one(
    integration_engine, shared_schema
):
    from editingtab_core.platform import services as platform

    with (
        scoped_connection(integration_engine, shared_schema) as connection,
        Session(connection) as session,
    ):
        for name in ("first", "second"):
            identity.create_user(session, email=f"{name}@example.test", display_name=name)
    pids = Queue()

    def attempt(name):
        with scoped_connection(integration_engine, shared_schema) as connection:
            pid = connection.scalar(text("SELECT pg_backend_pid()"))
            connection.commit()
            pids.put(pid)
            with Session(connection) as session:
                try:
                    platform.bootstrap_initial(session, email=f"{name}@example.test")
                    return "granted"
                except platform.BootstrapClosed:
                    return "closed"

    with scoped_connection(integration_engine, shared_schema) as gate:
        gate.execute(text("SELECT id FROM core_platform_bootstrap WHERE id = 1 FOR UPDATE"))
        with ThreadPoolExecutor(max_workers=2) as workers:
            futures = [workers.submit(attempt, name) for name in ("first", "second")]
            try:
                worker_pids = [pids.get(timeout=3), pids.get(timeout=3)]
                deadline = time.monotonic() + 2
                with integration_engine.connect() as observer:
                    while True:
                        waiting = [
                            observer.scalar(
                                text("SELECT cardinality(pg_blocking_pids(:pid)) > 0"), {"pid": pid}
                            )
                            for pid in worker_pids
                        ]
                        if all(waiting):
                            break
                        assert time.monotonic() < deadline, (
                            "Bootstrap workers did not reach concurrent locks"
                        )
                        time.sleep(0.01)
            finally:
                gate.rollback()
            assert sorted(f.result(timeout=5) for f in futures) == ["closed", "granted"]
    with scoped_connection(integration_engine, shared_schema) as connection:
        assert connection.scalar(text("SELECT count(*) FROM core_platform_admin_grants")) == 1
        assert (
            connection.scalar(
                text(
                    "SELECT count(*) FROM core_platform_audit "
                    "WHERE action = 'operator.bootstrap' AND actor_id IS NULL"
                )
            )
            == 1
        )
        assert (
            connection.scalar(
                text("SELECT completed_at IS NOT NULL FROM core_platform_bootstrap WHERE id = 1")
            )
            is True
        )
